create database project;
use project;
select *from product_table;
select *from supplier_table;
select *from logistic_table;
select *from sales_table;
select count(*) from product_table;
select count(*) from supplier_table;
select count(*) from logistic_table;
select count(*) from sales_table;
alter table product_table change ï»¿Poduct_id  product_id int;
select *from product_table where Product_id is null;
select Product_id,count(*) from product_table group by Product_id having count(*) > 1;
alter table product_table add primary key (Product_id);
describe  product_table;
alter table supplier_table change ï»¿Supplier_id supplier_id int;
select *from supplier_table where Supplier_id is null;
select Supplier_id,count(*) from supplier_table group by Supplier_id having count(*)>1;
alter table supplier_table add primary key(Supplier_id);
describe supplier_table;
alter table logistic_table change ï»¿Logistic_id logistic_id int;
select *from logistic_table where Logistic_id is null;
select Logistic_id,count(*) from logistic_table group by Logistic_id having count(*)>1;
alter table logistic_table add primary key(Logistic_id);
describe logistic_table;
alter table sales_table change ï»¿sales_id sales_id int;
alter table sales_table change poduct_id product_id int;
select *from sales_table where sales_id is null;
select sales_id ,count(*) from sales_table group by sales_id having count(*)>1;
alter table sales_table add primary key(sales_id);
describe sales_table;
alter table sales_table add constraint fk_sales_table_product_table foreign key (Product_id) references product_table(Product_id);
alter table sales_table add constraint fk_sales__supplier foreign key (Supplier_id) references supplier_table(Supplier_id);
alter table sales_table add constraint fk_sales__logistic foreign key (Logistic_id) references logistic_table(Logistic_id);
show create table sales_table;
SELECT product_type,SUM(number_of_products_sold) AS total_sold,RANK() OVER (ORDER BY SUM(number_of_products_sold) DESC) AS sale_rank FROM sales_table s JOIN product_table p ON s.product_id = p.Product_id GROUP BY product_type;
select supplier_name,sum(number_of_products_sold) as total_sold,RANK() over (order by sum(number_of_products_sold) DESC) as supplier_rank from sales_table s JOIN supplier_table p ON s.supplier_id = p.Supplier_id group by supplier_name;
select product_type,RANK() OVER (order by time_taken desc )as times_rank from (select p.product_type ,avg(lead_times)as time_taken from sales_table s join product_table p on s.product_id = p.Product_id group by product_type) final;
select product_type,sum(Availability)as total_available from product_table group by  product_type order by total_available DESC;
select customer_demographics,sum(number_of_products_sold)as total from sales_table group by customer_demographics order by total desc;
select product_type,sum(revenue_generated)as total_revenue from sales_table s join product_table p on s.product_id = p.product_id group by product_type order by total_revenue desc;
select product_type,avg(Costs)as total_cost from logistic_table l join sales_table s on l.logistic_id = s.logistic_id join product_table p on s.product_id = p.product_id group by product_type order by  total_cost desc;
select shipping_carriers,sum(number_of_products_sold) AS total_sold from sales_table s join logistic_table l on s.logistic_id = l.logistic_id group by shipping_carriers order by total_sold desc;
SELECT product_type,Inspection_results,COUNT(*) AS total_inspections FROM product_table p JOIN sales_table s ON p.product_id = s.product_id GROUP BY product_type, Inspection_results ORDER BY product_type, total_inspections DESC;
select location, sum(Number_of_products_sold)as total_sold from sales_table s join supplier_table p on s.supplier_id = p.supplier_id group by location order by total_sold desc;


